// 狀態碼常數
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  PERMISSION_DENIED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409, // 資料重複
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = { HTTP_STATUS };
